%% 六种DVL/INS组合导航结果对比
% 对比三种组合方式的15维、17维结果，不重新运行导航算法。

clear;
close all;
clc;

script_dir = fileparts(mfilename('fullpath'));
repo_root = fileparts(fileparts(script_dir));
addpath(fullfile(script_dir, 'function'));
addpath(fullfile(repo_root, 'psins2401', 'mytest', '00_all_func'));

%% 1. 对比参数：通常只修改这里
target_seed = 22;                 % 量测随机种子；设为[]时自动选择
target_input_id = '';             % 留空：自动选择六种结果最齐且最新的轨迹
target_range_beacon_index = 1;    % range信标编号；设为[]时取最新结果
result_root = fullfile(repo_root, 'data', 'graduation');

%% 2. 自动收集六种结果
[result, selection] = collect_six_algorithm_results(result_root, ...
    target_seed, target_input_id, target_range_beacon_index);

method_cn = ["INS+DVL（15维）"; "INS+DVL（17维）"; ...
    "INS+DVL+LBL（15维）"; "INS+DVL+LBL（17维）"; ...
    "INS+DVL+RANGE（15维）"; "INS+DVL+RANGE（17维）"];
combination_cn = ["INS+DVL"; "INS+DVL+LBL"; ...
    "INS+DVL+RANGE"];

output_dir = fullfile(result_root, 'comparison', ...
    sprintf('seed_%d', selection.measurement_seed), char(selection.input_id));
if ~exist(output_dir, 'dir')
    mkdir(output_dir);
end

%% 3. 保存六种算法的统一指标表
core_table = table(method_cn, result.dimension, ...
    result.position_rmse_n_m, result.position_rmse_e_m, ...
    result.position_rmse_d_m, result.velocity_rmse_n_mps, ...
    result.velocity_rmse_e_mps, result.velocity_rmse_d_mps, ...
    result.roll_rmse_deg, result.pitch_rmse_deg, result.yaw_rmse_deg, ...
    result.horizontal_rmse_m, result.horizontal_max_m, ...
    result.horizontal_final_m, result.horizontal_rmse_percent_course, ...
    result.horizontal_final_percent_course, ...
    'VariableNames', {'算法', '状态维数', '北向位置RMSE_m', ...
    '东向位置RMSE_m', '深度RMSE_m', '北向速度RMSE_mps', ...
    '东向速度RMSE_mps', '垂向速度RMSE_mps', '横滚RMSE_deg', ...
    '俯仰RMSE_deg', '航向RMSE_deg', '水平位置RMSE_m', ...
    '最大水平误差_m', '最终水平误差_m', '水平RMSE占航程_pct', ...
    '最终水平误差占航程_pct'});
writetable(core_table, fullfile(output_dir, '六种算法核心指标.csv'));

% 正值表示17维优于15维，负值表示17维变差。
index15 = [1, 3, 5];
index17 = [2, 4, 6];
improve = @(name) 100 * (result.(name)(index15) - ...
    result.(name)(index17)) ./ result.(name)(index15);
dimension_table = table(combination_cn, ...
    improve('position_rmse_n_m'), improve('position_rmse_e_m'), ...
    improve('position_rmse_d_m'), improve('velocity_rmse_n_mps'), ...
    improve('velocity_rmse_e_mps'), improve('velocity_rmse_d_mps'), ...
    improve('roll_rmse_deg'), improve('pitch_rmse_deg'), ...
    improve('yaw_rmse_deg'), improve('horizontal_rmse_m'), ...
    improve('horizontal_final_m'), ...
    improve('horizontal_rmse_percent_course'), ...
    improve('horizontal_final_percent_course'), ...
    'VariableNames', {'组合方式', '北向位置改善_pct', ...
    '东向位置改善_pct', '深度改善_pct', '北向速度改善_pct', ...
    '东向速度改善_pct', '垂向速度改善_pct', '横滚改善_pct', ...
    '俯仰改善_pct', '航向改善_pct', '水平RMSE改善_pct', ...
    '最终水平误差改善_pct', '水平航程误差改善_pct', ...
    '最终航程误差改善_pct'});
writetable(dimension_table, fullfile(output_dir, '15维到17维改善率.csv'));

% 读取step02保存的完整DVL参数估计结果。
dvl_calibration_data = cell(3, 1);
dvl_metric_rows = cell(3, 1);
for k = 1:3
    calibration_path = fullfile(result.result_dir(index17(k)), ...
        'dvl_calibration_error.csv');
    metric_path = fullfile(result.result_dir(index17(k)), ...
        'dvl_metrics.csv');
    if ~isfile(calibration_path) || ~isfile(metric_path)
        error('缺少17维DVL参数估计文件：%s', ...
            result.result_dir(index17(k)));
    end
    dvl_calibration_data{k} = readtable(calibration_path);
    dvl_metric_rows{k} = readtable(metric_path);
end
dvl_metric = vertcat(dvl_metric_rows{:});

dvl_table = table(combination_cn, dvl_metric.dvl_scale_true, ...
    dvl_metric.dvl_scale_final, dvl_metric.dvl_scale_tail_mean, ...
    dvl_metric.dvl_scale_final_abs_error, ...
    dvl_metric.dvl_scale_tail_rmse, dvl_metric.dvl_scale_final_std, ...
    100 * dvl_metric.dvl_scale_tail_1sigma_coverage, ...
    dvl_metric.dvl_yaw_true_deg, dvl_metric.dvl_yaw_final_deg, ...
    dvl_metric.dvl_yaw_tail_mean_deg, ...
    dvl_metric.dvl_yaw_final_abs_error_deg, ...
    dvl_metric.dvl_yaw_tail_rmse_deg, ...
    dvl_metric.dvl_yaw_final_std_deg, ...
    100 * dvl_metric.dvl_yaw_tail_1sigma_coverage, ...
    'VariableNames', {'组合方式', 'DVL刻度系数真值', ...
    'DVL刻度系数最终估计', 'DVL刻度系数末段均值', ...
    'DVL刻度系数最终绝对误差', 'DVL刻度系数末段RMSE', ...
    'DVL刻度系数最终标准差', 'DVL刻度系数末段1sigma覆盖率_pct', ...
    'DVL安装航向角真值_deg', 'DVL安装航向角最终估计_deg', ...
    'DVL安装航向角末段均值_deg', 'DVL安装航向角最终绝对误差_deg', ...
    'DVL安装航向角末段RMSE_deg', 'DVL安装航向角最终标准差_deg', ...
    'DVL安装航向角末段1sigma覆盖率_pct'});
writetable(dvl_table, fullfile(output_dir, '17维DVL参数估计对比.csv'));

fprintf('\n轨迹：%s，量测seed：%d\n', ...
    selection.input_id, selection.measurement_seed);
fprintf('正的改善率表示17维优于15维，负值表示17维变差。\n\n');
disp(core_table(:, {'算法', '北向位置RMSE_m', '东向位置RMSE_m', ...
    '水平位置RMSE_m', '最终水平误差_m', ...
    '最终水平误差占航程_pct', '航向RMSE_deg'}));
disp(dimension_table(:, {'组合方式', '水平RMSE改善_pct', ...
    '最终水平误差改善_pct', '最终航程误差改善_pct', ...
    '航向改善_pct'}));
disp(dvl_table(:, {'组合方式', 'DVL刻度系数真值', ...
    'DVL刻度系数最终估计', 'DVL刻度系数末段RMSE', ...
    'DVL安装航向角真值_deg', 'DVL安装航向角最终估计_deg', ...
    'DVL安装航向角末段RMSE_deg'}));

%% 4. 15维与17维核心指标成对比较
pair_colors = [0.55, 0.75, 0.95; 0.05, 0.35, 0.70];
metric_names = {'horizontal_rmse_m', 'horizontal_final_m', ...
    'horizontal_rmse_percent_course', 'yaw_rmse_deg'};
y_labels = {'水平位置RMSE / m', '最终水平误差 / m', ...
    '水平RMSE占航程 / %', '航向角RMSE / deg'};

fig1 = myfigurestartup(7,5,'paper');
tiledlayout(2, 2, 'TileSpacing', 'compact', 'Padding', 'compact');
for k = 1:numel(metric_names)
    ax = nexttile;
    values = [result.(metric_names{k})(index15), ...
        result.(metric_names{k})(index17)];
    bars = bar(ax, values, 'grouped');
    bars(1).FaceColor = pair_colors(1, :);
    bars(2).FaceColor = pair_colors(2, :);
    grid(ax, 'on');
    box(ax, 'on');
    ax.XTick = 1:3;
    ax.XTickLabel = cellstr(combination_cn);
    ax.TickLabelInterpreter = 'none';
    ylabel(ax, y_labels{k});
    if k == 1
        legend(ax, {'15维', '17维'}, 'Location', 'best');
    end
    for j = 1:2
        text(bars(j).XEndPoints, bars(j).YEndPoints, ...
            compose('%.3g', bars(j).YData), ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'bottom', 'FontSize', 8);
    end
end
sgtitle(sprintf('15维与17维结果对比（seed=%d）', ...
    selection.measurement_seed),'Fontname','TimesSimSun');
exportgraphics(fig1, fullfile(output_dir, '15维与17维核心指标对比.png'), ...
    'Resolution', 600);
savefig(fig1, fullfile(output_dir, '15维与17维核心指标对比.fig'));

%% 5. 水平误差与航程误差时序
line_colors = lines(3);
fig2 = myfigurestartup(7,5,'paper');
tiledlayout(2, 2, 'TileSpacing', 'compact', 'Padding', 'compact');
for dimension_index = 1:2
    case_index = dimension_index:2:6;

    ax1 = nexttile(dimension_index);
    hold(ax1, 'on');
    ax2 = nexttile(dimension_index + 2);
    hold(ax2, 'on');
    for k = 1:3
        time_series_path = fullfile(result.result_dir(case_index(k)), ...
            'navigation_error_timeseries.csv');
        error_data = readtable(time_series_path);
        time_h = error_data.time_s / 3600;
        plot(ax1, time_h, error_data.horizontal_error_m, ...
            'LineWidth', 1.15, 'Color', line_colors(k, :));
        
        course_error_percent = error_data.horizontal_error_percent_course;
        % 起步阶段航程太短，百分比的分母过小，不参与时序图显示。
        course_error_percent(error_data.cumulative_distance_m < 100) = nan;
        plot(ax2, time_h, course_error_percent, ...
            'LineWidth', 1.15, 'Color', line_colors(k, :));
        
    end
    xlim(ax1,[time_h(1) time_h(end)])
    xlim(ax2,[time_h(1) time_h(end)])
    grid(ax1, 'on'); box(ax1, 'on');
    grid(ax2, 'on'); box(ax2, 'on');
    title(ax1, sprintf('%d维：水平位置误差', ...
        result.dimension(case_index(1))));
    title(ax2, sprintf('%d维：水平误差占航程比例', ...
        result.dimension(case_index(1))));
    xlabel(ax1, '时间 / h'); ylabel(ax1, '水平误差 / m');
    xlabel(ax2, '时间 / h'); ylabel(ax2, '误差占航程 / %');
    legend(ax1, cellstr(combination_cn), 'Location', 'best');
end
exportgraphics(fig2, fullfile(output_dir, '六种算法水平误差时序.png'), ...
    'Resolution', 600);
savefig(fig2, fullfile(output_dir, '六种算法水平误差时序.fig'));

%% 6. 17维DVL安装角与刻度系数估计过程
estimate_color = [0.0000, 0.4470, 0.7410];
sigma_color = [0.45, 0.45, 0.45];
truth_color = [0.85, 0.10, 0.10];

fig3 = myfigurestartup(7, 5, 'paper');
tiledlayout(2, 3, 'TileSpacing', 'compact', 'Padding', 'compact');
for k = 1:3
    calibration = dvl_calibration_data{k};
    time_h = (calibration.time_s - calibration.time_s(1)) / 3600;

    ax_scale = nexttile(k);
    hold(ax_scale, 'on');
    h_estimate = plot(ax_scale, time_h, ...
        calibration.dvl_scale_estimate, '-', ...
        'Color', estimate_color, 'LineWidth', 1.2);
    h_upper = plot(ax_scale, time_h, ...
        calibration.dvl_scale_estimate + calibration.dvl_scale_std, '--', ...
        'Color', sigma_color, 'LineWidth', 0.8);
    h_lower = plot(ax_scale, time_h, ...
        calibration.dvl_scale_estimate - calibration.dvl_scale_std, '--', ...
        'Color', sigma_color, 'LineWidth', 0.8);
    yline(ax_scale, 0, 'k:', 'LineWidth', 0.8, ...
        'HandleVisibility', 'off');
    h_truth = yline(ax_scale, calibration.dvl_scale_true(1), ...
        '-.', '真值', 'Color', truth_color, 'LineWidth', 1.0);
    xlim(ax_scale, [time_h(1), time_h(end)]);
    grid(ax_scale, 'on'); box(ax_scale, 'on');
    title(ax_scale, combination_cn(k));
    xlabel(ax_scale, '时间 / h');
    ylabel(ax_scale, 'DVL刻度系数');
    if k == 1
        legend(ax_scale, [h_estimate, h_upper, h_lower, h_truth], ...
            {'估计值', '+1\sigma', '-1\sigma', '真值'}, ...
            'Location', 'best');
    end

    ax_yaw = nexttile(k + 3);
    hold(ax_yaw, 'on');
    h_estimate = plot(ax_yaw, time_h, ...
        calibration.dvl_yaw_estimate_deg, '-', ...
        'Color', estimate_color, 'LineWidth', 1.2);
    h_upper = plot(ax_yaw, time_h, ...
        calibration.dvl_yaw_estimate_deg + calibration.dvl_yaw_std_deg, '--', ...
        'Color', sigma_color, 'LineWidth', 0.8);
    h_lower = plot(ax_yaw, time_h, ...
        calibration.dvl_yaw_estimate_deg - calibration.dvl_yaw_std_deg, '--', ...
        'Color', sigma_color, 'LineWidth', 0.8);
    yline(ax_yaw, 0, 'k:', 'LineWidth', 0.8, ...
        'HandleVisibility', 'off');
    h_truth = yline(ax_yaw, calibration.dvl_yaw_true_deg(1), ...
        '-.', '真值', 'Color', truth_color, 'LineWidth', 1.0);
    xlim(ax_yaw, [time_h(1), time_h(end)]);
    grid(ax_yaw, 'on'); box(ax_yaw, 'on');
    xlabel(ax_yaw, '时间 / h');
    ylabel(ax_yaw, 'DVL安装航向角 / deg');
    if k == 1
        legend(ax_yaw, [h_estimate, h_upper, h_lower, h_truth], ...
            {'估计值', '+1\sigma', '-1\sigma', '真值'}, ...
            'Location', 'best');
    end
end
sgtitle('17维DVL参数估计过程', 'FontName', 'TimesSimSun');
exportgraphics(fig3, fullfile(output_dir, ...
    '17维DVL参数估计过程对比.png'), 'Resolution', 600);
savefig(fig3, fullfile(output_dir, '17维DVL参数估计过程对比.fig'));

%% 7. 三种组合方式的DVL参数估计误差直接对比
fig4 = myfigurestartup(7, 2.5, 'paper');
tiledlayout(1, 2, 'TileSpacing', 'compact', 'Padding', 'compact');
ax_scale_error = nexttile;
hold(ax_scale_error, 'on');
ax_yaw_error = nexttile;
hold(ax_yaw_error, 'on');
for k = 1:3
    calibration = dvl_calibration_data{k};
    time_h = (calibration.time_s - calibration.time_s(1)) / 3600;
    plot(ax_scale_error, time_h, calibration.dvl_scale_error, ...
        'Color', line_colors(k, :), 'LineWidth', 1.2);
    plot(ax_yaw_error, time_h, calibration.dvl_yaw_error_deg, ...
        'Color', line_colors(k, :), 'LineWidth', 1.2);
end
yline(ax_scale_error, 0, 'k:', 'LineWidth', 0.8, ...
    'HandleVisibility', 'off');
yline(ax_yaw_error, 0, 'k:', 'LineWidth', 0.8, ...
    'HandleVisibility', 'off');
xlim(ax_scale_error, [0, time_h(end)]);
xlim(ax_yaw_error, [0, time_h(end)]);
grid(ax_scale_error, 'on'); box(ax_scale_error, 'on');
grid(ax_yaw_error, 'on'); box(ax_yaw_error, 'on');
xlabel(ax_scale_error, '时间 / h');
ylabel(ax_scale_error, 'DVL刻度系数估计误差');
title(ax_scale_error, '刻度系数误差');
xlabel(ax_yaw_error, '时间 / h');
ylabel(ax_yaw_error, 'DVL安装航向角估计误差 / deg');
title(ax_yaw_error, '安装航向角误差');
legend(ax_scale_error, cellstr(combination_cn), 'Location', 'best');
legend(ax_yaw_error, cellstr(combination_cn), 'Location', 'best');
exportgraphics(fig4, fullfile(output_dir, ...
    '17维DVL参数估计误差对比.png'), 'Resolution', 600);
savefig(fig4, fullfile(output_dir, '17维DVL参数估计误差对比.fig'));

fprintf('对比结果已保存到：\n%s\n', output_dir);
