function summary = save_dvl_ins_metrics(navpath, truthpath, simulation_path, ...
    imu_error_path, dvl_calibration_path, result_dir, run_info)
%SAVE_DVL_INS_METRICS Save navigation, IMU and DVL estimation metrics.

param = Param();
nav = readmatrix(navpath, 'FileType', 'text');
truth = readmatrix(truthpath, 'FileType', 'text');

nav_data = nav(:, 2:end);
truth_data = truth(:, 2:end);
nav_data(:, 10) = rad2deg(unwrap(deg2rad(nav_data(:, 10))));
truth_data(:, 10) = rad2deg(unwrap(deg2rad(truth_data(:, 10))));

time_s = nav_data(:, 1);
valid = time_s >= truth_data(1, 1) & time_s <= truth_data(end, 1);
nav_data = nav_data(valid, :);
time_s = time_s(valid);
truth_interp = interp1(truth_data(:, 1), truth_data(:, 2:10), ...
    time_s, 'linear');

raw_error = nav_data(:, 2:10) - truth_interp;
raw_error(:, 9) = mod(raw_error(:, 9) + 180, 360) - 180;
sample_count = size(raw_error, 1);
lat_rad = truth_interp(:, 1) * param.D2R;
lon_rad = truth_interp(:, 2) * param.D2R;
height_m = truth_interp(:, 3);
earth_term = 1 - param.WGS84_E1 * sin(lat_rad) .^ 2;
rm = param.WGS84_RA * (1 - param.WGS84_E1) ./ ...
    (sqrt(earth_term) .* earth_term);
rn = param.WGS84_RA ./ sqrt(earth_term);
position_error_ned_m = [raw_error(:, 1) * param.D2R .* (rm + height_m), ...
    raw_error(:, 2) * param.D2R .* (rn + height_m) .* cos(lat_rad), ...
    -raw_error(:, 3)];

mean_lat_rad = 0.5 * (lat_rad(2:end) + lat_rad(1:end-1));
mean_height_m = 0.5 * (height_m(2:end) + height_m(1:end-1));
earth_term_mid = 1 - param.WGS84_E1 * sin(mean_lat_rad) .^ 2;
rm_mid = param.WGS84_RA * (1 - param.WGS84_E1) ./ ...
    (sqrt(earth_term_mid) .* earth_term_mid);
rn_mid = param.WGS84_RA ./ sqrt(earth_term_mid);
delta_north_m = diff(lat_rad) .* (rm_mid + mean_height_m);
delta_east_m = diff(lon_rad) .* (rn_mid + mean_height_m) .* ...
    cos(mean_lat_rad);
cumulative_distance_m = [0; cumsum(hypot(delta_north_m, delta_east_m))];

velocity_error_ned_mps = raw_error(:, 4:6);
attitude_error_rpy_deg = raw_error(:, 7:9);
horizontal_error_m = hypot(position_error_ned_m(:, 1), ...
    position_error_ned_m(:, 2));
course_error_percent = 100 * horizontal_error_m ./ cumulative_distance_m;
course_error_percent(cumulative_distance_m < 1) = nan;

output_stride = max(1, round(run_info.diagnostic_record_interval_s / ...
    median(diff(time_s))));
output_index = unique([1:output_stride:sample_count, sample_count])';
error_table = table(time_s(output_index) - time_s(1), ...
    position_error_ned_m(output_index, 1), ...
    position_error_ned_m(output_index, 2), ...
    position_error_ned_m(output_index, 3), horizontal_error_m(output_index), ...
    velocity_error_ned_mps(output_index, 1), ...
    velocity_error_ned_mps(output_index, 2), ...
    velocity_error_ned_mps(output_index, 3), ...
    attitude_error_rpy_deg(output_index, 1), ...
    attitude_error_rpy_deg(output_index, 2), ...
    attitude_error_rpy_deg(output_index, 3), ...
    cumulative_distance_m(output_index), course_error_percent(output_index), ...
    'VariableNames', {'time_s', ...
    'position_error_n_m', 'position_error_e_m', 'position_error_d_m', ...
    'horizontal_error_m', 'velocity_error_n_mps', ...
    'velocity_error_e_mps', 'velocity_error_d_mps', ...
    'roll_error_deg', 'pitch_error_deg', 'yaw_error_deg', ...
    'cumulative_distance_m', 'horizontal_error_percent_course'});
writetable(error_table, fullfile(result_dir, ...
    'navigation_error_timeseries.csv'));

position_rmse = sqrt(mean(position_error_ned_m .^ 2, 1));
velocity_rmse = sqrt(mean(velocity_error_ned_mps .^ 2, 1));
attitude_rmse = sqrt(mean(attitude_error_rpy_deg .^ 2, 1));
horizontal_rmse_m = sqrt(mean(horizontal_error_m .^ 2));
travel_distance_m = cumulative_distance_m(end);
final_horizontal_error_m = horizontal_error_m(end);
if travel_distance_m > 0
    horizontal_rmse_percent_course = 100 * horizontal_rmse_m / ...
        travel_distance_m;
    horizontal_final_percent_course = 100 * final_horizontal_error_m / ...
        travel_distance_m;
else
    horizontal_rmse_percent_course = nan;
    horizontal_final_percent_course = nan;
end

summary = table(string(run_info.combination_type), run_info.dimension, ...
    run_info.case_index, run_info.measurement_seed, run_info.feedback, ...
    run_info.aiding_interval_s, run_info.range_noise_std_m, ...
    run_info.lbl_position_noise_std_m, run_info.beacon_index, ...
    run_info.beacon_enu_m(1), run_info.beacon_enu_m(2), ...
    run_info.beacon_enu_m(3), ...
    string(run_info.trajectory_tag), string(run_info.input_id), ...
    run_info.input_duration_s, time_s(end) - time_s(1), sample_count, ...
    run_info.range_update_count, run_info.lbl_update_count, ...
    travel_distance_m, position_rmse(1), position_rmse(2), ...
    position_rmse(3), velocity_rmse(1), velocity_rmse(2), ...
    velocity_rmse(3), attitude_rmse(1), attitude_rmse(2), ...
    attitude_rmse(3), horizontal_rmse_m, max(horizontal_error_m), ...
    final_horizontal_error_m, horizontal_rmse_percent_course, ...
    horizontal_final_percent_course, ...
    'VariableNames', {'combination_type', 'dimension', 'case_index', ...
    'measurement_seed', 'feedback', 'aiding_interval_s', ...
    'range_noise_std_m', 'lbl_position_noise_std_m', 'beacon_index', ...
    'beacon_e_m', 'beacon_n_m', 'beacon_u_m', 'trajectory_tag', ...
    'input_id', 'input_duration_s', ...
    'processed_duration_s', 'sample_count', 'range_update_count', ...
    'lbl_update_count', 'travel_distance_m', 'position_rmse_n_m', ...
    'position_rmse_e_m', 'position_rmse_d_m', 'velocity_rmse_n_mps', ...
    'velocity_rmse_e_mps', 'velocity_rmse_d_mps', 'roll_rmse_deg', ...
    'pitch_rmse_deg', 'yaw_rmse_deg', 'horizontal_rmse_m', ...
    'horizontal_max_m', 'horizontal_final_m', ...
    'horizontal_rmse_percent_course', 'horizontal_final_percent_course'});

summary.gyro_bias_final_error_norm_dph = nan;
summary.acc_bias_final_error_norm_mgal = nan;
summary.dvl_scale_true = nan;
summary.dvl_scale_final = nan;
summary.dvl_scale_tail_rmse = nan;
summary.dvl_yaw_true_deg = nan;
summary.dvl_yaw_final_deg = nan;
summary.dvl_yaw_tail_rmse_deg = nan;

simulation = struct();
if isfile(simulation_path)
    simulation = load(simulation_path, 'cfg', 'imu_error');
end
summary.simulation_seed = nan;
if isfield(simulation, 'cfg') && isfield(simulation.cfg, 'random_seed')
    summary.simulation_seed = simulation.cfg.random_seed;
end

if ~isempty(imu_error_path) && isfile(imu_error_path)
    imu_metrics = save_imu_metrics(imu_error_path, simulation, result_dir);
    summary.gyro_bias_final_error_norm_dph = ...
        imu_metrics.gyro_bias_final_error_norm_dph;
    summary.acc_bias_final_error_norm_mgal = ...
        imu_metrics.acc_bias_final_error_norm_mgal;
end

if ~isempty(dvl_calibration_path) && isfile(dvl_calibration_path)
    dvl_metrics = save_dvl_metrics(dvl_calibration_path, simulation, result_dir);
    summary.dvl_scale_true = dvl_metrics.dvl_scale_true;
    summary.dvl_scale_final = dvl_metrics.dvl_scale_final;
    summary.dvl_scale_tail_rmse = dvl_metrics.dvl_scale_tail_rmse;
    summary.dvl_yaw_true_deg = dvl_metrics.dvl_yaw_true_deg;
    summary.dvl_yaw_final_deg = dvl_metrics.dvl_yaw_final_deg;
    summary.dvl_yaw_tail_rmse_deg = dvl_metrics.dvl_yaw_tail_rmse_deg;
end

writetable(summary, fullfile(result_dir, 'performance_summary.csv'));
end


function metrics = save_imu_metrics(path, simulation, result_dir)
data = readmatrix(path, 'FileType', 'text');
estimate = data(:, 2:13);
true_value = nan(1, 12);

if isfield(simulation, 'imu_error')
    imu_error = simulation.imu_error;
    gyro_rfu_dph = imu_error.eb(:)' * 180 / pi * 3600;
    accel_rfu_mgal = imu_error.db(:)' * 1e5;
    gyro_scale_rfu_ppm = diag(imu_error.dKg)' * 1e6;
    accel_scale_rfu_ppm = diag(imu_error.dKa)' * 1e6;
    true_value(1:3) = [gyro_rfu_dph(2), gyro_rfu_dph(1), ...
        -gyro_rfu_dph(3)];
    true_value(4:6) = [accel_rfu_mgal(2), accel_rfu_mgal(1), ...
        -accel_rfu_mgal(3)];
    true_value(7:9) = [gyro_scale_rfu_ppm(2), ...
        gyro_scale_rfu_ppm(1), gyro_scale_rfu_ppm(3)];
    true_value(10:12) = [accel_scale_rfu_ppm(2), ...
        accel_scale_rfu_ppm(1), accel_scale_rfu_ppm(3)];
end

error_value = estimate - true_value;
names = {'gyro_bias_x_dph', 'gyro_bias_y_dph', 'gyro_bias_z_dph', ...
    'acc_bias_x_mgal', 'acc_bias_y_mgal', 'acc_bias_z_mgal', ...
    'gyro_scale_x_ppm', 'gyro_scale_y_ppm', 'gyro_scale_z_ppm', ...
    'acc_scale_x_ppm', 'acc_scale_y_ppm', 'acc_scale_z_ppm'};
output = table(data(:, 1), 'VariableNames', {'time_s'});
for k = 1:numel(names)
    output.([names{k}, '_estimate']) = estimate(:, k);
    output.([names{k}, '_true']) = repmat(true_value(k), size(data, 1), 1);
    output.([names{k}, '_error']) = error_value(:, k);
end
writetable(output, fullfile(result_dir, 'imu_estimation_error.csv'));

tail_index = max(1, floor(0.9 * size(data, 1))):size(data, 1);
tail_rmse = sqrt(mean(error_value(tail_index, :) .^ 2, 1, 'omitnan'));
final_error = error_value(end, :);
metrics = table(norm(final_error(1:3)), norm(final_error(4:6)), ...
    norm(tail_rmse(1:3)), norm(tail_rmse(4:6)), ...
    'VariableNames', {'gyro_bias_final_error_norm_dph', ...
    'acc_bias_final_error_norm_mgal', 'gyro_bias_tail_rmse_norm_dph', ...
    'acc_bias_tail_rmse_norm_mgal'});
writetable(metrics, fullfile(result_dir, 'imu_metrics.csv'));
end


function metrics = save_dvl_metrics(path, simulation, result_dir)
data = readmatrix(path, 'FileType', 'text');
true_scale = nan;
true_yaw_deg = nan;
if isfield(simulation, 'cfg')
    if isfield(simulation.cfg, 'dvl_scale_error')
        true_scale = simulation.cfg.dvl_scale_error;
    end
    if isfield(simulation.cfg, 'dvl_install_pry_deg')
        true_yaw_deg = simulation.cfg.dvl_install_pry_deg(3);
    end
end

scale_error = data(:, 2) - true_scale;
yaw_error_deg = data(:, 3) - true_yaw_deg;
output = table(data(:, 1), data(:, 2), repmat(true_scale, size(data, 1), 1), ...
    scale_error, data(:, 4), data(:, 3), ...
    repmat(true_yaw_deg, size(data, 1), 1), yaw_error_deg, data(:, 5), ...
    'VariableNames', {'time_s', 'dvl_scale_estimate', 'dvl_scale_true', ...
    'dvl_scale_error', 'dvl_scale_std', 'dvl_yaw_estimate_deg', ...
    'dvl_yaw_true_deg', 'dvl_yaw_error_deg', 'dvl_yaw_std_deg'});
writetable(output, fullfile(result_dir, 'dvl_calibration_error.csv'));

tail_index = max(1, floor(0.9 * size(data, 1))):size(data, 1);
scale_tail_rmse = sqrt(mean(scale_error(tail_index) .^ 2, 'omitnan'));
yaw_tail_rmse_deg = sqrt(mean(yaw_error_deg(tail_index) .^ 2, 'omitnan'));
scale_coverage = mean(abs(scale_error(tail_index)) <= data(tail_index, 4), ...
    'omitnan');
yaw_coverage = mean(abs(yaw_error_deg(tail_index)) <= data(tail_index, 5), ...
    'omitnan');
metrics = table(true_scale, data(end, 2), mean(data(tail_index, 2)), ...
    abs(scale_error(end)), scale_tail_rmse, data(end, 4), scale_coverage, ...
    true_yaw_deg, data(end, 3), mean(data(tail_index, 3)), ...
    abs(yaw_error_deg(end)), yaw_tail_rmse_deg, data(end, 5), yaw_coverage, ...
    'VariableNames', {'dvl_scale_true', 'dvl_scale_final', ...
    'dvl_scale_tail_mean', 'dvl_scale_final_abs_error', ...
    'dvl_scale_tail_rmse', 'dvl_scale_final_std', ...
    'dvl_scale_tail_1sigma_coverage', 'dvl_yaw_true_deg', ...
    'dvl_yaw_final_deg', 'dvl_yaw_tail_mean_deg', ...
    'dvl_yaw_final_abs_error_deg', 'dvl_yaw_tail_rmse_deg', ...
    'dvl_yaw_final_std_deg', 'dvl_yaw_tail_1sigma_coverage'});
writetable(metrics, fullfile(result_dir, 'dvl_metrics.csv'));
end
