function outputs = run_engineering_navigation_case( ...
        dataset, result_dir, range_data, runtime_options)
%RUN_ENGINEERING_NAVIGATION_CASE 用统一接口运行仿真或实测 EKF/RTS。
if nargin < 4 || isempty(runtime_options), runtime_options = struct(); end
unit = lower(string(option_value(runtime_options, ...
    'position_error_unit', 'rad')));
duration_s = option_value(runtime_options, 'duration_s', 4621);
filter_range_std_m = option_value(runtime_options, ...
    'filter_range_std_m', 10);
enable_rotation = logical(option_value(runtime_options, ...
    'enable_rotation', false));

if dataset.data_source == "simulation"
    options = struct( ...
        'position_error_unit', unit, ...
        'range_data', range_data, ...
        'range_noise_std_m', 0, ...
        'filter_range_std_m', filter_range_std_m, ...
        'random_seed', option_value(runtime_options, 'random_seed', 1), ...
        'end_time_s', duration_s);
    outputs = simulate_navigation_case(char(dataset.dataset_id), ...
        result_dir, false, false, options);
else
    if unit ~= "rad"
        error(['当前实测扩展核心采用 rad 位置误差状态；', ...
            'data_source="experiment" 时请设置 position_error_unit="rad"。']);
    end
    options = struct( ...
        'case_name', char(option_value(runtime_options, ...
            'case_name', 'engineering-experiment-rad')), ...
        'range_data', range_data, ...
        'duration_s', duration_s, ...
        'filter_range_std_m', filter_range_std_m, ...
        'enable_rotation', enable_rotation, ...
        'enable_fixed_lag_replay', false);
    outputs = run_navigation_experiment(result_dir, options);
end
end

function value = option_value(options, field_name, default_value)
%OPTION_VALUE 读取可选字段。
    if isfield(options, field_name) && ~isempty(options.(field_name))
        value = options.(field_name);
    else
        value = default_value;
    end
end
