clear;
clc;
close all;
%% ============================================================
% Release - Beacon 三维相对位置示意
%
% 坐标系：ENU
%   x : East
%   y : North
%   z : Up
%
% 海面       z = 0
% Beacon     z = -1200 m
% Release    z = -3000 m
%
% 倾角 theta：下段系泊相对于竖直方向的等效倾角
%% ============================================================
%% 1. 工程参数
D_release = 3000;      % Release 深度 / m
D_beacon  = 1200;      % Beacon 深度 / m
H = D_release - D_beacon;   % 垂向跨度，约1800 m
theta_deg = 1.0;       % 等效倾角 / deg，可修改
azimuth_deg = 45;      % 水平漂移方向，0°=东，90°=北
%% 2. 根据倾角计算水平漂移
r = H * tand(theta_deg);
fprintf('====================================\n');
fprintf('垂向跨度 H       = %.2f m\n', H);
fprintf('倾角 theta       = %.2f deg\n', theta_deg);
fprintf('水平漂移 r       = %.2f m\n', r);
fprintf('Release-Beacon距离 = %.2f m\n', sqrt(H^2+r^2));
fprintf('====================================\n');
%% 3. 三维坐标
% Release
R = [0, 0, -D_release];
% Beacon 水平偏移
dE = r * cosd(azimuth_deg);
dN = r * sind(azimuth_deg);
B = [dE, dN, -D_beacon];
% Beacon 在海底平面的垂直投影
P = [dE, dN, -D_release];
%% ============================================================
% 4. 三维绘图
% ============================================================
figure('Color','w', ...
       'Position',[100 80 1100 760]);
hold on;
grid on;
box on;
%% ------------------------------------------------------------
% 海底平面
% -------------------------------------------------------------
planeSize = max(200, 2.2*r);
[xBottom,yBottom] = meshgrid( ...
    linspace(-planeSize,planeSize,2), ...
    linspace(-planeSize,planeSize,2));
zBottom = -D_release * ones(size(xBottom));
surf(xBottom,yBottom,zBottom, ...
    'FaceAlpha',0.15, ...
    'EdgeColor','none');
%% ------------------------------------------------------------
% 海面
% -------------------------------------------------------------
zSurface = zeros(size(xBottom));
surf(xBottom,yBottom,zSurface, ...
    'FaceAlpha',0.06, ...
    'EdgeColor','none');
%% ------------------------------------------------------------
% Release
% -------------------------------------------------------------
scatter3( ...
    R(1),R(2),R(3), ...
    120, ...
    'filled');
text( ...
    R(1),R(2),R(3)-70, ...
    'Release 点 R', ...
    'FontSize',12, ...
    'FontWeight','bold', ...
    'HorizontalAlignment','center');
%% ------------------------------------------------------------
% Beacon
% -------------------------------------------------------------
scatter3( ...
    B(1),B(2),B(3), ...
    120, ...
    'filled');
text( ...
    B(1),B(2),B(3)+100, ...
    sprintf('发声点 B\n深度 %.0f m',D_beacon), ...
    'FontSize',12, ...
    'FontWeight','bold', ...
    'HorizontalAlignment','center');
%% ------------------------------------------------------------
% 下段张紧系泊
% -------------------------------------------------------------
plot3( ...
    [R(1),B(1)], ...
    [R(2),B(2)], ...
    [R(3),B(3)], ...
    'k-', ...
    'LineWidth',2.5);
midPoint = 0.55*R + 0.45*B;
text( ...
    midPoint(1), ...
    midPoint(2), ...
    midPoint(3), ...
    '  下段张紧系泊', ...
    'FontSize',11);
%% ------------------------------------------------------------
% Beacon 垂直投影
% -------------------------------------------------------------
plot3( ...
    [B(1),P(1)], ...
    [B(2),P(2)], ...
    [B(3),P(3)], ...
    'k--', ...
    'LineWidth',1.3);
scatter3( ...
    P(1),P(2),P(3), ...
    40, ...
    'filled');
%% ------------------------------------------------------------
% 水平漂移 r
% -------------------------------------------------------------
plot3( ...
    [R(1),P(1)], ...
    [R(2),P(2)], ...
    [R(3),P(3)], ...
    '--', ...
    'LineWidth',1.8);
r_mid = (R+P)/2;
text( ...
    r_mid(1), ...
    r_mid(2), ...
    r_mid(3)+60, ...
    sprintf('r = %.1f m',r), ...
    'FontSize',12, ...
    'FontWeight','bold');
%% ------------------------------------------------------------
% 垂向跨度 H
% -------------------------------------------------------------
H_pos = P + [0.15*planeSize, 0, 0];
plot3( ...
    [H_pos(1),H_pos(1)], ...
    [H_pos(2),H_pos(2)], ...
    [-D_release,-D_beacon], ...
    'k--', ...
    'LineWidth',1.3);
text( ...
    H_pos(1), ...
    H_pos(2), ...
    -(D_release+D_beacon)/2, ...
    sprintf('  H = %.0f m',H), ...
    'FontSize',12);
%% ============================================================
% 5. 倾角 theta 示意
% ============================================================
% 在 Release 附近画一个小角度圆弧
arcLength = min(300,0.25*H);
alpha = linspace(0,theta_deg,60);
% 倾角相对竖直方向
arc_r = arcLength;
arc_E = ...
    R(1) + arc_r .* sind(alpha) .* cosd(azimuth_deg);
arc_N = ...
    R(2) + arc_r .* sind(alpha) .* sind(azimuth_deg);
arc_Z = ...
    R(3) + arc_r .* cosd(alpha);
plot3( ...
    arc_E,arc_N,arc_Z, ...
    'LineWidth',2);
text( ...
    arc_E(end), ...
    arc_N(end), ...
    arc_Z(end)+30, ...
    sprintf('\\theta = %.1f^\\circ',theta_deg), ...
    'FontSize',12, ...
    'FontWeight','bold');
%% ============================================================
% 6. ENU坐标轴
% ============================================================
axisLength = 150;
origin = R;
quiver3( ...
    origin(1),origin(2),origin(3), ...
    axisLength,0,0, ...
    0,'LineWidth',1.7);
quiver3( ...
    origin(1),origin(2),origin(3), ...
    0,axisLength,0, ...
    0,'LineWidth',1.7);
quiver3( ...
    origin(1),origin(2),origin(3), ...
    0,0,axisLength, ...
    0,'LineWidth',1.7);
text( ...
    origin(1)+axisLength, ...
    origin(2), ...
    origin(3), ...
    ' E');
text( ...
    origin(1), ...
    origin(2)+axisLength, ...
    origin(3), ...
    ' N');
text( ...
    origin(1), ...
    origin(2), ...
    origin(3)+axisLength, ...
    ' U');
%% ============================================================
% 7. 图形设置
% ============================================================
xlabel('East / m');
ylabel('North / m');
zlabel('Up / m');
title({ ...
    'Release - Beacon 三维相对位置', ...
    sprintf('\\theta = %.1f^\\circ,  H = %.0f m,  r = %.1f m', ...
    theta_deg,H,r)});
view(38,22);
xlim([-planeSize planeSize]);
ylim([-planeSize planeSize]);
zlim([-D_release-100 100]);
%% 水平和垂向真实比例差异非常大，
% 因此这里不使用 axis equal，
% 否则几十米水平漂移在1800m垂向跨度下几乎看不出来。
set(gca,'FontSize',11);
%% ============================================================
% 8. 额外画一张俯视图
% ============================================================
figure('Color','w', ...
       'Position',[250 150 700 650]);
hold on;
grid on;
box on;
axis equal;
scatter(R(1),R(2),120,'filled');
scatter(B(1),B(2),120,'filled');
plot( ...
    [R(1),B(1)], ...
    [R(2),B(2)], ...
    'k-', ...
    'LineWidth',2);
text( ...
    R(1),R(2), ...
    '  Release R', ...
    'FontSize',12);
text( ...
    B(1),B(2), ...
    sprintf('  Beacon B (r = %.1f m)',r), ...
    'FontSize',12);
xlabel('East / m');
ylabel('North / m');
title(sprintf( ...
    '俯视图：\\theta = %.1f^\\circ 对应水平漂移 %.1f m', ...
    theta_deg,r));
margin = max(20,0.3*r);
xlim([min(R(1),B(1))-margin, ...
      max(R(1),B(1))+margin]);
ylim([min(R(2),B(2))-margin, ...
      max(R(2),B(2))+margin]);