clear;
clc;
close all;

%% 数据路径
dataset = 1 ;
switch dataset
    case 1
        rootDir = ...
            'D:\Github\KF-GINS-Matlab\data\inertial-experiment\data-0817';
        load(fullfile(rootDir,'raw_data_0817.mat'));
    case 2
        rootDir = ...
            'D:\Github\KF-GINS-Matlab\data\inertial-experiment\data-0818';
        load(fullfile(rootDir,'raw_data_0818.mat'));
    case 3
        rootDir = ...
            'D:\Github\KF-GINS-Matlab\data\inertial-experiment\data-0818-1';
        load(fullfile(rootDir,'raw_data_0818_1.mat'));
end
inputDir=[rootDir,'\input'];
fprintf("原始数据加载完成\n");
%% 时间范围
% tStart = 103951.090;
tStart =IMU_raw(find(IMU_raw(:,1)>431, 1),1);
% if ~isempty(IMU_raw(IMU_raw(:,1)==0.005))
%     id = find(IMU_raw(:,1)==0.005);
%     index = find(IMU_raw(id:end,1)>430.015);
%     tStart = IMU_raw(min(index)+id,1);
% end
% tEnd   = 117644.180;
tEnd = IMU_raw(end,1);
time_tol = 0.006;
%% 1. 处理830参考导航
nav830 = GPCHCX_830;
% 去除无效状态
nav830 = nav830(:,nav830(21,:)~=0);
nav830(2,:)=nav830(2,:)-18;
% 时间截取
idx = ...
    nav830(2,:)>=tStart & ...
    nav830(2,:)<=tEnd;
nav830 = nav830(:,idx);
% 转PVA
close all
[~,pva830] = visualize_gpchcx_navigation_results(nav830);
name{1}=[rootDir,'/pva'];
name{2}=[rootDir,'/error_statics'];
all_figs = findobj('Type','figure');  % 获取当前全部打开的figure句柄
for f = all_figs.'
    f_id = f.Number;
    filename_base = name{f_id};  
    savefig(f, [filename_base '.fig']);
    exportgraphics(f, [filename_base '.png'], 'Resolution',600);
end
disp('全部fig、png导出完成');
%% 2. 830插值100Hz
time830 = ...
    pva830(1,2):0.01:pva830(end,2);
pva830_interp=zeros(length(time830),11);
pva830_interp(:,2)=time830';
pva830_interp(:,3:11)=interp1(...
    pva830(:,2),...
    pva830(:,3:11),...
    time830,...
    'linear');
%% 3. Range误差分析
fprintf("\n========== 830和实际构造Range分析 ==========\n");
Hrange = range_error_analysis(...
    range_raw,...
    pva830_interp,...
    time_tol);
range_830=range_raw;
range_830(:,3)=Hrange;
%% 3.1 Range误差分析
auxa = auxa_raw;
[~, ss] = min(abs(auxa(:,1) - tStart));
[~, ee] = min(abs(auxa(:,1) - tEnd));
auxa = auxa(ss:ee,:);
fprintf("\n========== 120和实际构造Range分析 ==========\n");
Hrange=range_error_analysis(...
    range_raw,...
    auxa(:,[2,1,3:end]),...
    time_tol);
range_120=range_raw;
range_120(:,3)=Hrange;
%% 4. Depth误差分析
depth_error_analysis(...
    depth_raw,...
    auxa,...
    pva830_interp);
fprintf("\n全部分析完成\n");
%% 输出830参考导航结果
output_file = fullfile(inputDir, 'pva_830.txt');

writeMatrixSafe( ...
    pva830_interp, ...
    output_file, ...
    '830导航信息');
%% 处理并导出120IMU数据
imu_start_index = find(abs(IMU_raw(:,1)-tStart)<0.006);
IMU_120 = IMU_raw(imu_start_index:end, [2:7,1]);
checkdata11(IMU_120(:,end));
% 坐标系转换

IMU_120 = imuFUR2FRD( ...
    [IMU_120, IMU_120(:,end)]);
output_file = fullfile(inputDir, 'imu_120.txt');
writeMatrixSafe( ...
    IMU_120, ...
    output_file, ...
    '惯性数据');
%% 导出原始距离数据
output_file = fullfile(inputDir, 'range.txt');
writeMatrixSafe( ...
    range_raw, ...
    output_file, ...
    '原始距离数据');
output_file = fullfile(inputDir, 'range_120.txt');
writeMatrixSafe( ...
    range_120, ...
    output_file, ...
    '原始120构造距离数据');
output_file = fullfile(inputDir, 'range_830.txt');
writeMatrixSafe( ...
    range_830, ...
    output_file, ...
    '原始830构造距离数据');

%% 导出原始深度数据
output_file = fullfile(inputDir, ...
    'depth_raw.txt');
writeMatrixSafe( ...
    depth_raw, ...
    output_file, ...
    '原始深度数据');
%% 导出120参考数据
output_file = fullfile(inputDir, ...
    'pva_120.txt');
writeMatrixSafe( ...
    auxa(:,[2,1,3:end]), ...
    output_file, ...
    '120数据');
GNSS = auxa(1:100:end,:);
output_file = fullfile(inputDir, ...
    'GNSS_1s.txt');
writeMatrixSafe( ...
    GNSS(:,[1,3:5,6:8]), ...
    output_file, ...
    'GNSS数据');
%%  函数
function range_ref=range_error_analysis(range,pva830,time_tol)
% 根据830位置计算水平距离
% 时间匹配
[index,valid]=findNearestTimeIndex(...
    range(:,1),...
    pva830(:,2),...
    time_tol);
range=range(valid,:);
index=index(valid);
% 参考位置
pos830=pva830(index,3:5);
% deg->rad
pos830(:,1:2)=deg2rad(pos830(:,1:2));
% 转局部坐标
glvs
% xyz830=pos2dxyz(pos830, pos830(1,:)');
% 信标位置
beacon=range(:,4:6);
% xyzBeacon=pos2dxyz(beacon,pos830(1,:)');
% 水平距离
% range_ref=sqrt((xyzBeacon(:,1)-xyz830(:,1)).^2 + (xyzBeacon(:,2)-xyz830(:,2)).^2);
range_ref=RCompu(beacon,pos830);

range_meas=range(:,3);
% 残差
error=range_meas-range_ref;
fprintf("Range数量:%d\n",length(error));
fprintf("Mean = %.3f m\n",mean(error));
fprintf("RMSE = %.3f m\n",...
    sqrt(mean(error.^2)));
fprintf("MAX = %.3f m\n",...
    max(abs(error)));
%% 绘图
figure;
plot(error,...
    'LineWidth',1.2);
grid on;
xlabel("测距序号");
ylabel("Range error / m");
title("声学测距水平距离误差");
end
%% 函数
function depth_error_analysis(...
    depth,...
    auxa,...
    pva830)

fprintf("\n========== Depth分析 ==========\n");
%% 时间轴
t=depth(:,1);
depth_sensor=depth(:,2);
%% AUXA120
depth120=interp1(...
    auxa(:,1),...
    auxa(:,5),...
    t,...
    'linear',...
    NaN);
%% 830
depth830=interp1(...
    pva830(:,2),...
    pva830(:,5),...
    t,...
    'linear',...
    NaN);
%% 有效数据
valid=...
    ~isnan(depth120)&...
    ~isnan(depth830);
depth_sensor=depth_sensor(valid);
depth120=depth120(valid);
depth830=depth830(valid);
tt = t(valid);
%% 如果方向相反
% depth120=-depth120;
% depth830=-depth830;
%% 误差
err120=depth120-depth_sensor;
err830=depth830-depth_sensor;
fprintf("\n120-Depth RMSE %.3f m\n",...
    sqrt(mean(err120.^2)));
fprintf("830-Depth RMSE %.3f m\n",...
    sqrt(mean(err830.^2)));
%% 图
figure;
plot(tt-tt(1),depth_sensor,...
    'LineWidth',1.2);
hold on;
plot(tt-tt(1),depth120,...
    'LineWidth',1.2);
plot(tt-tt(1),depth830,...
    'LineWidth',1.2);
grid on;
legend(...
    'Depth sensor',...
    '120',...
    '830');
xlabel("Time/s");
ylabel("Depth/m");
title("深度结果对比");
figure;
plot(tt-tt(1),err120,...
    'LineWidth',1.2);
hold on;
plot(tt-tt(1),err830,...
    'LineWidth',1.2);
grid on;
legend(...
    '120-Depth',...
    '830-Depth');
xlabel("Time/s");
ylabel("Error/m");
title("深度误差");
end
%% 时间最近邻匹配
function [index, valid] = findNearestTimeIndex(...
    targetTime,...
    sourceTime,...
    time_tol)
n = length(targetTime);
index = nan(n,1);
valid = false(n,1);
for i = 1:n
    % 找最近时间点
    [dt_min, idx] = min(...
        abs(sourceTime-targetTime(i)));
    % 判断是否满足容差
    if dt_min <= time_tol
        index(i)=idx;
        valid(i)=true;

    else

        warning(...
            ['第 %d 个Range时间 %.6f ',...
            '没有匹配点，最小时间差 %.6f s'],...
            i,...
            targetTime(i),...
            dt_min);
    end
end
end
%%
function writeMatrixSafe( ...
    data, ...
    output_file, ...
    dataName)
try
    writematrix( ...
        data, ...
        output_file, ...
        'Delimiter',' ');
    fprintf( ...
        '%s已写入：%s\n', ...
        dataName, ...
        output_file);
catch ME
    error( ...
        '%s写入失败：%s', ...
        dataName, ...
        ME.message);
end
end
%%
function checkdata11(a)
d = diff(a);
tol = 1e-10;
step = 0.01;
missing_indices = find( ...
    d > (step + tol));
if isempty(missing_indices)
    disp('该向量是完整的0.01 s等差时间序列，无缺失数据。');
else
    disp('发现缺失数据：');
    for i = 1:length(missing_indices)
        idx = missing_indices(i);
        num_missing = ...
            round(d(idx)/step)-1;
        start_val = a(idx);
        end_val   = a(idx+1);
        fprintf( ...
            ['在 a(%d)=%.6f 和 ', ...
            'a(%d)=%.6f 之间，', ...
            '缺失 %d 个数据。\n'], ...
            idx, ...
            start_val, ...
            idx+1, ...
            end_val, ...
            num_missing);
    end
end
end