function Export120 = export_static_120_inputs( ...
        dataset_ids, alignment_time_s, save_result, caseNo, imu_rate_hz)
% EXPORT_STATIC_120_INPUTS Build navigation-ready files for either static batch.
%
%   Export120 = export_static_120_inputs()
%   Export120 = export_static_120_inputs(dataset_ids)
%   Export120 = export_static_120_inputs(dataset_ids, alignment_time_s)
%   Export120 = export_static_120_inputs(dataset_ids, alignment_time_s, save_result)
%   Export120 = export_static_120_inputs(..., caseNo)
%   Export120 = export_static_120_inputs(..., caseNo, imu_rate_hz)
%
% Empty/omitted dataset_ids selects only the dataset with the longest
% STDIMU duration. Pass an ID explicitly to inspect a discarded short run.
% Empty imu_rate_hz keeps the native STDIMU rate. A lower rate must be an
% integer divisor of the native rate; static-2 therefore supports 100/200 Hz.
%
% The function uses static_120_raw.mat generated by parse_static_120:
%   1. Convert STDIMU FUR measurements with imuFUR2FRD.
%   2. Use AUXA at about 430 s as the common time/initial-state anchor.
%   3. Export the pre-anchor IMU as alignment data.
%   4. Export the post-anchor IMU and PVA as navigation inputs.
%
% No PVA interpolation or gap filling is performed. A dataset that does not
% reach the requested alignment time is skipped instead of using its last
% record as a false initial state.
%
% Default output for the single effective acquisition:
%   <repo>/data/experiment-data/<static|static-x>/input/
%       IMU_120.txt          post-alignment navigation IMU, 7 columns
%       IMU_120_static.txt   pre-alignment IMU, 7 columns
%       pva_file.txt         PVA beginning at the selected initial point
%       pva_initial.txt      one-row initial PVA
%       pva_all.txt          incomplete AUXA-derived PVA, gaps retained
%       pva_incomplete.txt   explicit alias of pva_all.txt
%       ref_pva.txt          constant initial PVA on the complete IMU time axis
%       AUXA_IMU_FRD.txt     incomplete AUXA embedded IMU after unit/axis conversion
%       imu_alignment_check.csv  AUXA IMU versus STDIMU alignment statistics
%       static_120_input.mat MATLAB copy of the exported arrays and metadata
%
% IMU_120 column format:
%   [time, dtheta_x, dtheta_y, dtheta_z, dvel_x, dvel_y, dvel_z]
%
% PVA column format (same as experiment-01/02):
%   [machine_time, nav_time, lat, lon, height, vn, ve, vd,
%    roll, pitch, heading]

if nargin < 1
    dataset_ids = [];
end
if nargin < 2 || isempty(alignment_time_s)
    alignment_time_s = 430.010;
end
if nargin < 3 || isempty(save_result)
    save_result = true;
end
if nargin < 4 || isempty(caseNo)
    caseNo = 0;
end
if nargin < 5
    imu_rate_hz = [];
end

validateattributes(alignment_time_s, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'nonnegative'}, mfilename, 'alignment_time_s', 2);
validateattributes(save_result, {'logical', 'numeric'}, {'scalar'}, ...
    mfilename, 'save_result', 3);
save_result = logical(save_result);
validateattributes(caseNo, {'numeric'}, ...
    {'scalar', 'integer', 'nonnegative', '<=', 5}, mfilename, 'caseNo', 4);
if ~isempty(imu_rate_hz)
    validateattributes(imu_rate_hz, {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'}, ...
        mfilename, 'imu_rate_hz', 5);
end

code_dir = fileparts(mfilename('fullpath'));
analysis_dir = fileparts(code_dir);
repo_dir = fileparts(analysis_dir);
if caseNo == 0
    batch_name = 'static';
else
    batch_name = sprintf('static-%d', caseNo);
end
data_dir = fullfile(repo_dir, 'data', 'experiment-data', ...
    batch_name);
processed_file = fullfile(data_dir, 'processed', 'static_120_raw.mat');
input_root = fullfile(data_dir, 'input');
convert_dir = fullfile(repo_dir, 'function_zxy', 'referconvert');

if exist('imuFUR2FRD', 'file') ~= 2
    if ~isfolder(convert_dir)
        error('export_static_120_inputs:MissingConversionDirectory', ...
            'Conversion function directory does not exist: %s', convert_dir);
    end
    addpath(convert_dir);
end

if ~isfile(processed_file)
    fprintf('Parsed raw MAT file was not found; running parse_static_120 first.\n');
    Static120 = parse_static_120([], true, caseNo);
else
    loaded = load(processed_file, 'Static120');
    Static120 = loaded.Static120;
end

available_ids = [Static120.id];
if isempty(dataset_ids)
    stdimu_duration = arrayfun(@(item) ...
        item.info.stdimu_time.duration, Static120);
    [~, selected_indices] = max(stdimu_duration);
    ignored_ids = setdiff(available_ids, available_ids(selected_indices), 'stable');
    if ~isempty(ignored_ids)
        fprintf(['Default selection keeps the longest STDIMU dataset %03d; ' ...
            'short dataset(s) %s are ignored.\n'], ...
            available_ids(selected_indices), id_text(ignored_ids));
    end
else
    validateattributes(dataset_ids, {'numeric'}, ...
        {'vector', 'integer', 'nonnegative', 'finite'}, mfilename, 'dataset_ids', 1);
    dataset_ids = unique(dataset_ids(:).', 'stable');
    missing_ids = setdiff(dataset_ids, available_ids);
    if ~isempty(missing_ids)
        error('export_static_120_inputs:UnknownDataset', ...
            'Parsed data does not contain ID(s): %s', id_text(missing_ids));
    end
    selected_indices = zeros(size(dataset_ids));
    for k = 1:numel(dataset_ids)
        selected_indices(k) = find(available_ids == dataset_ids(k), 1);
    end
end

if numel(selected_indices) ~= 1
    error('export_static_120_inputs:MultipleDatasetsNotSupported', ...
        ['The flat input directory represents one effective acquisition. ' ...
         'Select exactly one dataset ID.']);
end

anchor_tolerance_s = 0.050;
imu_match_tolerance_s = 0.050;
n_dataset = numel(selected_indices);
Export120 = repmat(empty_export(), 1, n_dataset);

fprintf('\n============================================================\n');
fprintf('Export navigation-ready 120 static data\n');
fprintf('Alignment target: %.3f s\n', alignment_time_s);
fprintf('Dataset IDs: %s\n', id_text(available_ids(selected_indices)));
fprintf('============================================================\n');

for out_index = 1:n_dataset
    source = Static120(selected_indices(out_index));
    auxa = source.auxa_raw;
    imu_fur_raw = source.imu_raw;
    result = empty_export();
    result.id = source.id;
    result.name = source.name;
    result.status = 'pending';
    result.reason = '';

    fprintf('\n[%d/%d] %s\n', out_index, n_dataset, source.name);

    pva_all = auxa_to_pva(auxa);
    auxa_imu_fur = auxa(12:17, :).';
    % AUXA embeds acceleration in g, while Disk2 STDIMU uses m/s^2.
    % Convert the unit before applying the common FUR -> FRD transform.
    auxa_imu_fur(:, 4:6) = auxa_imu_fur(:, 4:6) * 9.80665;
    auxa_machine_time = pva_all(:, 1);
    [anchor_error_s, pva_anchor_index] = min(abs(auxa_machine_time - alignment_time_s));

    if isempty(pva_anchor_index) || anchor_error_s > anchor_tolerance_s
        result.status = 'skipped';
        result.reason = sprintf(...
            'AUXA does not cover %.3f s (last record %.3f s).', ...
            alignment_time_s, auxa_machine_time(end));
        result.info = struct(...
            'alignment_target_s', alignment_time_s, ...
            'auxa_end_s', auxa_machine_time(end), ...
            'anchor_error_s', anchor_error_s);
        Export120(out_index) = result;
        warning('export_static_120_inputs:AlignmentNotCovered', ...
            '%s skipped: %s', source.name, result.reason);
        continue;
    end

    pva_initial = pva_all(pva_anchor_index, :);
    pva_file = pva_all(pva_anchor_index:end, :);
    auxa_anchor_machine_time = pva_initial(1);
    anchor_nav_time = pva_initial(2);

    imu_machine_time = double(imu_fur_raw(:, 7)) / 200;
    [imu_anchor_error_s, imu_anchor_index] = min(...
        abs(imu_machine_time - auxa_anchor_machine_time));
    if isempty(imu_anchor_index) || imu_anchor_error_s > imu_match_tolerance_s
        result.status = 'skipped';
        result.reason = sprintf(...
            'STDIMU has no record matching AUXA anchor %.3f s.', ...
            auxa_anchor_machine_time);
        result.info = struct(...
            'alignment_target_s', alignment_time_s, ...
            'auxa_anchor_machine_time_s', auxa_anchor_machine_time, ...
            'imu_anchor_error_s', imu_anchor_error_s);
        Export120(out_index) = result;
        warning('export_static_120_inputs:IMUMatchFailed', ...
            '%s skipped: %s', source.name, result.reason);
        continue;
    end

    native_dt_s = median(diff(imu_machine_time));
    native_rate_hz = 1 / native_dt_s;
    if isempty(imu_rate_hz)
        requested_rate_hz = native_rate_hz;
    else
        requested_rate_hz = imu_rate_hz;
    end
    decimation_factor = round(native_rate_hz / requested_rate_hz);
    if decimation_factor < 1 || ...
            abs(native_rate_hz / requested_rate_hz - decimation_factor) > 1e-3
        error('export_static_120_inputs:UnsupportedIMURate', ...
            ['Requested IMU rate %.6g Hz must be an integer divisor of ' ...
             'the native rate %.6g Hz.'], ...
            requested_rate_hz, native_rate_hz);
    end
    [imu_fur_raw, imu_machine_time, imu_anchor_index] = ...
        aggregate_imu_rate_samples(imu_fur_raw, imu_machine_time, ...
        imu_anchor_index, decimation_factor);
    actual_rate_hz = 1 / median(diff(imu_machine_time));

    % Anchor the STDIMU time axis to AUXA navigation time. The early part
    % remains continuous and the selected IMU sample shares the PVA time.
    imu_nav_time = anchor_nav_time + ...
        (imu_machine_time - auxa_anchor_machine_time);
    imu_fur = imu_fur_raw;
    imu_fur(:, 8) = imu_nav_time;
    imu_sample_interval_s = sample_intervals(imu_machine_time);
    imu_all = imuFUR2FRD(imu_fur, imu_sample_interval_s);

    auxa_imu_input = [auxa_imu_fur, zeros(size(auxa_imu_fur, 1), 1), ...
        pva_all(:, 2)];
    auxa_sample_interval_s = sample_intervals(auxa_machine_time);
    auxa_imu_frd = imuFUR2FRD(auxa_imu_input, auxa_sample_interval_s);
    imu_alignment = compare_auxa_stdimu(...
        auxa_machine_time, auxa_imu_frd, auxa_sample_interval_s, ...
        imu_machine_time, imu_all, imu_sample_interval_s, ...
        auxa_anchor_machine_time);

    imu_static = imu_all(1:imu_anchor_index - 1, :);
    imu_120 = imu_all(imu_anchor_index:end, :);
    if isempty(imu_120)
        error('export_static_120_inputs:EmptyNavigationIMU', ...
            '%s produced an empty post-alignment IMU.', source.name);
    end

    % Static reference used to evaluate pure INS drift. Its two time columns
    % follow the complete post-alignment IMU; all state columns remain equal
    % to the aligned initial PVA without interpolation or later AUXA updates.
    ref_pva = repmat(pva_initial, size(imu_120, 1), 1);
    ref_pva(:, 1) = imu_machine_time(imu_anchor_index:end);
    ref_pva(:, 2) = imu_120(:, 1);

    nav_time_gap = diff(pva_file(:, 2));
    positive_gap = nav_time_gap(nav_time_gap > 0 & isfinite(nav_time_gap));
    if isempty(positive_gap)
        nominal_pva_dt = NaN;
        pva_gap_count = 0;
    else
        nominal_pva_dt = median(positive_gap);
        gap_threshold = max(0.050, 5 * nominal_pva_dt);
        pva_gap_count = sum(nav_time_gap > gap_threshold);
    end

    info = struct();
    info.alignment_target_s = alignment_time_s;
    info.pva_anchor_index = pva_anchor_index;
    info.pva_anchor_machine_time_s = auxa_anchor_machine_time;
    info.pva_anchor_nav_time_s = anchor_nav_time;
    info.pva_anchor_error_s = anchor_error_s;
    info.imu_anchor_index = imu_anchor_index;
    info.imu_anchor_machine_time_s = imu_machine_time(imu_anchor_index);
    info.imu_anchor_error_s = imu_anchor_error_s;
    info.native_imu_rate_hz = native_rate_hz;
    info.requested_imu_rate_hz = requested_rate_hz;
    info.actual_imu_rate_hz = actual_rate_hz;
    info.imu_decimation_factor = decimation_factor;
    info.initial_pva = pva_initial;
    info.imu_static_records = size(imu_static, 1);
    info.imu_navigation_records = size(imu_120, 1);
    info.pva_all_records = size(pva_all, 1);
    info.pva_navigation_records = size(pva_file, 1);
    info.ref_pva_records = size(ref_pva, 1);
    info.pva_gap_count = pva_gap_count;
    info.nominal_pva_dt_s = nominal_pva_dt;
    info.nominal_auxa_imu_dt_s = median(auxa_sample_interval_s);
    info.nominal_stdimu_dt_s = median(imu_sample_interval_s);
    info.time_alignment_error_s = imu_120(1, 1) - pva_initial(2);
    info.auxa_imu_records = size(auxa_imu_frd, 1);
    info.auxa_imu_matched_records = imu_alignment.matched_records;
    info.auxa_imu_exact_time_records = imu_alignment.exact_time_records;
    info.auxa_imu_shifted_time_records = imu_alignment.shifted_time_records;
    info.auxa_imu_max_time_error_s = imu_alignment.max_time_error_s;
    info.post_alignment_gyro_rmse_dps = ...
        imu_alignment.post_alignment.rmse_physical(1:3);
    info.post_alignment_accel_rmse_mps2 = ...
        imu_alignment.post_alignment.rmse_physical(4:6);

    result.status = 'exported';
    result.pva_all = pva_all;
    result.pva_file = pva_file;
    result.pva_initial = pva_initial;
    result.ref_pva = ref_pva;
    result.imu_all = imu_all;
    result.imu_static = imu_static;
    result.imu_120 = imu_120;
    result.auxa_imu_frd = auxa_imu_frd;
    result.imu_alignment = imu_alignment;
    result.info = info;

    output_dir = input_root;
    result.output_dir = output_dir;
    if save_result
        if ~isfolder(output_dir)
            mkdir(output_dir);
        end
        writematrix(imu_120, fullfile(output_dir, 'IMU_120.txt'), 'Delimiter', ' ');
        writematrix(imu_static, fullfile(output_dir, 'IMU_120_static.txt'), 'Delimiter', ' ');
        writematrix(pva_file, fullfile(output_dir, 'pva_file.txt'), 'Delimiter', ' ');
        writematrix(pva_initial, fullfile(output_dir, 'pva_initial.txt'), 'Delimiter', ' ');
        writematrix(pva_all, fullfile(output_dir, 'pva_all.txt'), 'Delimiter', ' ');
        writematrix(pva_all, fullfile(output_dir, 'pva_incomplete.txt'), 'Delimiter', ' ');
        writematrix(ref_pva, fullfile(output_dir, 'ref_pva.txt'), 'Delimiter', ' ');
        writematrix(auxa_imu_frd, ...
            fullfile(output_dir, 'AUXA_IMU_FRD.txt'), 'Delimiter', ' ');
        writetable(imu_alignment.table, ...
            fullfile(output_dir, 'imu_alignment_check.csv'));

        export_info = info;
        imu_alignment_table = imu_alignment.table;
        save(fullfile(output_dir, 'static_120_input.mat'), ...
            'imu_120', 'imu_static', 'imu_all', 'pva_file', ...
            'pva_initial', 'pva_all', 'ref_pva', 'auxa_imu_frd', ...
            'imu_alignment', 'imu_alignment_table', 'export_info', '-v7.3');
    end

    Export120(out_index) = result;
    fprintf('  Initial PVA: machine %.3f s, nav %.3f s\n', ...
        pva_initial(1), pva_initial(2));
    fprintf('  Initial attitude [roll pitch heading]: %.6f %.6f %.6f deg\n', ...
        pva_initial(9), pva_initial(10), pva_initial(11));
    fprintf('  IMU alignment/navigation: %d / %d records\n', ...
        size(imu_static, 1), size(imu_120, 1));
    fprintf('  IMU rate: native %.3f Hz -> output %.3f Hz (factor %d)\n', ...
        native_rate_hz, actual_rate_hz, decimation_factor);
    fprintf('  PVA navigation: %d records, retained gap count: %d\n', ...
        size(pva_file, 1), pva_gap_count);
    fprintf('  Constant reference PVA: %d records, %.3f ~ %.3f s\n', ...
        size(ref_pva, 1), ref_pva(1, 2), ref_pva(end, 2));
    fprintf('  IMU/PVA start-time error: %+.9f s\n', info.time_alignment_error_s);
    fprintf('  AUXA IMU matched to STDIMU: %d/%d records\n', ...
        imu_alignment.matched_records, size(auxa_imu_frd, 1));
    fprintf('  Match time error: max %.3f ms (%d exact, %d shifted)\n', ...
        1000 * imu_alignment.max_time_error_s, ...
        imu_alignment.exact_time_records, imu_alignment.shifted_time_records);
    fprintf('  Post-alignment gyro RMSE [deg/s]: %.6g %.6g %.6g\n', ...
        info.post_alignment_gyro_rmse_dps);
    fprintf('  Post-alignment accel RMSE [m/s^2]: %.6g %.6g %.6g\n', ...
        info.post_alignment_accel_rmse_mps2);
    if save_result
        fprintf('  Output: %s\n', output_dir);
    end
end

summary_table = build_summary(Export120);
if save_result
    if ~isfolder(input_root)
        mkdir(input_root);
    end
    writetable(summary_table, fullfile(input_root, 'static_120_export_summary.csv'));
end

fprintf('\n============================================================\n');
fprintf('Exported: %d; skipped: %d\n', ...
    sum(strcmp({Export120.status}, 'exported')), ...
    sum(strcmp({Export120.status}, 'skipped')));
fprintf('============================================================\n');
end

function pva = auxa_to_pva(auxa)
if size(auxa, 1) ~= 34
    error('export_static_120_inputs:InvalidAUXA', ...
        'AUXA input must be a 34-by-N matrix.');
end
nav = auxa.';
heading = mod(-nav(:, 3), 360);
pva = [nav(:, 1:2), nav(:, 6:10), zeros(size(nav, 1), 1), ...
    nav(:, 5), nav(:, 4), heading];
end

function [imu_raw, imu_time, anchor_index] = aggregate_imu_rate_samples( ...
        imu_raw, imu_time, anchor_index, factor)
% Downsample rate-form IMU data while preserving the PVA anchor sample.
% Each retained row is the mean of the native-rate samples in the interval
% ending at that row; conversion to increments happens afterwards.

if factor == 1
    return;
end

left_endpoint = anchor_index:-factor:1;
left_endpoint = fliplr(left_endpoint);
right_endpoint = (anchor_index + factor):factor:size(imu_raw, 1);
endpoint = [left_endpoint, right_endpoint];

averaged_measurement = movmean(imu_raw(:, 1:6), ...
    [factor - 1, 0], 1, 'Endpoints', 'shrink');
resampled = imu_raw(endpoint, :);
resampled(:, 1:6) = averaged_measurement(endpoint, :);

imu_raw = resampled;
imu_time = imu_time(endpoint);
anchor_index = numel(left_endpoint);
end

function interval_s = sample_intervals(time_s)
% Convert a time axis to per-record integration intervals. Isolated gaps
% use the nominal interval so a missing record is not synthesized by
% integrating one instantaneous rate across the whole gap.

time_s = double(time_s(:));
delta_s = diff(time_s);
positive_delta_s = delta_s(delta_s > 0 & isfinite(delta_s));
if isempty(positive_delta_s)
    error('export_static_120_inputs:InvalidTimeAxis', ...
        'Cannot determine a positive IMU sample interval.');
end
nominal_dt_s = median(positive_delta_s);
interval_s = repmat(nominal_dt_s, numel(time_s), 1);
regular = delta_s > 0 & delta_s <= 5 * nominal_dt_s;
regular_index = find(regular);
interval_s(regular_index + 1) = delta_s(regular_index);
end

function comparison = compare_auxa_stdimu(auxa_time, auxa_frd, auxa_dt_s, ...
        stdimu_time, stdimu_frd, stdimu_dt_s, alignment_time)
% Pair each AUXA record with an existing nearest STDIMU sample. No signal
% interpolation is performed. AUXA contains several 5 ms timestamp-phase
% sections, so a 5.1 ms pairing tolerance is intentionally allowed.

stdimu_index_axis = (1:numel(stdimu_time)).';
nearest_index = interp1(stdimu_time, stdimu_index_axis, auxa_time, ...
    'nearest', NaN);
valid = isfinite(nearest_index);
nearest_index(valid) = round(nearest_index(valid));
auxa_index = find(valid);
stdimu_index = nearest_index(valid);
time_error = stdimu_time(stdimu_index) - auxa_time(auxa_index);
within_tolerance = abs(time_error) <= 0.0051;
auxa_index = auxa_index(within_tolerance);
stdimu_index = stdimu_index(within_tolerance);
time_error = time_error(within_tolerance);

auxa_rate = auxa_frd(auxa_index, 2:7) ./ auxa_dt_s(auxa_index);
stdimu_rate = stdimu_frd(stdimu_index, 2:7) ./ ...
    stdimu_dt_s(stdimu_index);
difference = auxa_rate - stdimu_rate;
sample_time = auxa_time(auxa_index);

comparison = struct();
comparison.matched_records = numel(auxa_index);
comparison.exact_time_records = sum(abs(time_error) < 1e-6);
comparison.shifted_time_records = sum(abs(time_error) >= 1e-6);
comparison.max_time_error_s = max(abs(time_error));
comparison.auxa_index = auxa_index;
comparison.stdimu_index = stdimu_index;
comparison.time_error_s = time_error;
comparison.overall = alignment_statistics(...
    difference, auxa_rate, stdimu_rate);

alignment_mask = sample_time < alignment_time;
post_alignment_mask = sample_time >= alignment_time;
comparison.alignment = alignment_statistics(...
    difference(alignment_mask, :), ...
    auxa_rate(alignment_mask, :), ...
    stdimu_rate(alignment_mask, :));
comparison.post_alignment = alignment_statistics(...
    difference(post_alignment_mask, :), ...
    auxa_rate(post_alignment_mask, :), ...
    stdimu_rate(post_alignment_mask, :));
comparison.table = alignment_statistics_table(comparison);
end

function stats = alignment_statistics(difference, auxa_value, stdimu_value)
stats = struct();
stats.records = size(difference, 1);
if isempty(difference)
    stats.rmse_output = nan(1, 6);
    stats.mean_output = nan(1, 6);
    stats.maxabs_output = nan(1, 6);
    stats.rmse_physical = nan(1, 6);
    stats.correlation = nan(1, 6);
    return;
end

stats.rmse_output = sqrt(mean(difference .^ 2, 1));
stats.mean_output = mean(difference, 1);
stats.maxabs_output = max(abs(difference), [], 1);

physical_difference = difference;
physical_difference(:, 1:3) = ...
    physical_difference(:, 1:3) * 180 / pi;
stats.rmse_physical = sqrt(mean(physical_difference .^ 2, 1));

stats.correlation = nan(1, 6);
for channel = 1:6
    correlation_matrix = corrcoef(...
        auxa_value(:, channel), stdimu_value(:, channel));
    if all(size(correlation_matrix) == [2, 2])
        stats.correlation(channel) = correlation_matrix(1, 2);
    end
end
end

function statistics_table = alignment_statistics_table(comparison)
phase_fields = {'overall', 'alignment', 'post_alignment'};
phase_labels = {'all', 'alignment', 'post_alignment'};
channel_names = {'gyro_x', 'gyro_y', 'gyro_z', ...
    'accel_x', 'accel_y', 'accel_z'};
output_units = {'rad/s', 'rad/s', 'rad/s', ...
    'm/s^2', 'm/s^2', 'm/s^2'};
physical_units = {'deg/s', 'deg/s', 'deg/s', ...
    'm/s^2', 'm/s^2', 'm/s^2'};

n_row = numel(phase_fields) * numel(channel_names);
phase = strings(n_row, 1);
channel = strings(n_row, 1);
records = zeros(n_row, 1);
rmse_output = nan(n_row, 1);
mean_output = nan(n_row, 1);
maxabs_output = nan(n_row, 1);
output_unit = strings(n_row, 1);
rmse_physical = nan(n_row, 1);
physical_unit = strings(n_row, 1);
correlation = nan(n_row, 1);

row = 0;
for phase_index = 1:numel(phase_fields)
    stats = comparison.(phase_fields{phase_index});
    for channel_index = 1:numel(channel_names)
        row = row + 1;
        phase(row) = string(phase_labels{phase_index});
        channel(row) = string(channel_names{channel_index});
        records(row) = stats.records;
        rmse_output(row) = stats.rmse_output(channel_index);
        mean_output(row) = stats.mean_output(channel_index);
        maxabs_output(row) = stats.maxabs_output(channel_index);
        output_unit(row) = string(output_units{channel_index});
        rmse_physical(row) = stats.rmse_physical(channel_index);
        physical_unit(row) = string(physical_units{channel_index});
        correlation(row) = stats.correlation(channel_index);
    end
end

statistics_table = table(phase, channel, records, rmse_output, ...
    mean_output, maxabs_output, output_unit, rmse_physical, ...
    physical_unit, correlation);
end

function result = empty_export()
result = struct(...
    'id', [], ...
    'name', '', ...
    'status', '', ...
    'reason', '', ...
    'output_dir', '', ...
    'pva_all', [], ...
    'pva_file', [], ...
    'pva_initial', [], ...
    'ref_pva', [], ...
    'imu_all', [], ...
    'imu_static', [], ...
    'imu_120', [], ...
    'auxa_imu_frd', [], ...
    'imu_alignment', struct(), ...
    'info', struct());
end

function summary = build_summary(data)
n = numel(data);
id = zeros(n, 1);
name = strings(n, 1);
status = strings(n, 1);
reason = strings(n, 1);
anchor_machine_time_s = nan(n, 1);
anchor_nav_time_s = nan(n, 1);
native_imu_rate_hz = nan(n, 1);
output_imu_rate_hz = nan(n, 1);
imu_static_records = zeros(n, 1);
imu_navigation_records = zeros(n, 1);
pva_navigation_records = zeros(n, 1);
ref_pva_records = zeros(n, 1);
pva_gap_count = zeros(n, 1);
time_alignment_error_s = nan(n, 1);
auxa_imu_matched_records = zeros(n, 1);
auxa_imu_max_time_error_ms = nan(n, 1);
post_gyro_rmse_max_dps = nan(n, 1);
post_accel_rmse_max_mps2 = nan(n, 1);

for k = 1:n
    id(k) = data(k).id;
    name(k) = string(data(k).name);
    status(k) = string(data(k).status);
    reason(k) = string(data(k).reason);
    if strcmp(data(k).status, 'exported')
        info = data(k).info;
        anchor_machine_time_s(k) = info.pva_anchor_machine_time_s;
        anchor_nav_time_s(k) = info.pva_anchor_nav_time_s;
        native_imu_rate_hz(k) = info.native_imu_rate_hz;
        output_imu_rate_hz(k) = info.actual_imu_rate_hz;
        imu_static_records(k) = info.imu_static_records;
        imu_navigation_records(k) = info.imu_navigation_records;
        pva_navigation_records(k) = info.pva_navigation_records;
        ref_pva_records(k) = info.ref_pva_records;
        pva_gap_count(k) = info.pva_gap_count;
        time_alignment_error_s(k) = info.time_alignment_error_s;
        auxa_imu_matched_records(k) = info.auxa_imu_matched_records;
        auxa_imu_max_time_error_ms(k) = 1000 * info.auxa_imu_max_time_error_s;
        post_gyro_rmse_max_dps(k) = max(info.post_alignment_gyro_rmse_dps);
        post_accel_rmse_max_mps2(k) = max(info.post_alignment_accel_rmse_mps2);
    end
end

summary = table(id, name, status, reason, anchor_machine_time_s, ...
    anchor_nav_time_s, native_imu_rate_hz, output_imu_rate_hz, ...
    imu_static_records, imu_navigation_records, ...
    pva_navigation_records, ref_pva_records, pva_gap_count, ...
    time_alignment_error_s, ...
    auxa_imu_matched_records, auxa_imu_max_time_error_ms, ...
    post_gyro_rmse_max_dps, post_accel_rmse_max_mps2);
end

function text = id_text(ids)
if isempty(ids)
    text = '(none)';
else
    text = strjoin(compose('%03d', ids), ', ');
end
end
